
import type { Metadata } from "next";
import { Inter , Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { Context } from "@/context/context";

const inter = Poppins({ subsets: ['latin'] , weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          <Header />
          {children}
        </Context>
      </body>
    </html>
  );
}
